# Generated by Django 5.1.3 on 2025-01-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_e_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='e_Product',
        ),
    ]
