# Generated by Django 5.1.3 on 2025-02-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='menglasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='products/')),
                ('name', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
