# Generated by Django 5.1.3 on 2025-02-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_menglasses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='menglasses_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='menglasses',
        ),
    ]
