# Generated by Django 5.1.3 on 2025-02-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='glasses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.glasses'),
        ),
    ]
